### ISSUE TITLE
wifi tracking stopped working after latest update

### ISSUE THREAD

**Issue by iceaway** [mathisdt/trackworktime#145]
Hi!

I have been using the app for a while with wifi-based tracking, and it has been working just fine. But after the last update wifi-tracking no longer works. In the logs i see this all the time:
```
2021-03-02 00:00:10 DEBUG WifiScanner.requestWifiScanResults - Requested wifi scan results
2021-03-02 00:00:10 DEBUG WifiScanner.requestWifiScanResults - Wifi start scan succeeded: false
2021-03-02 00:00:10 INFO  WifiTracker.onScanRequestFailed - wifi scan request failed, skipping wifi check - retaining previous tracking state
```
Battery optimization is off for the app. The version I'm running is 1.1.3. It has storage and location permissions. Says that no permissions are denied. Anything else I'm missing?

**Comment by jahnf** [comment]
I have the same issue. For me WiFi tracking and location tracking is not working anymore with latest update(s).

Battery optimization is off.

On Android 11.

**Comment by mathisdt** [comment]
Thanks for the feedback! I identified one major issue with version 1.1.3: it doesn't ask for all necessary permissions on Android 10+! As I only have an Android 9 device, I didn't experience this problem - plus the coarse location tracking I use is not testable on the emulator (GPS would be testable)... :grimacing: 

I fixed this (and some other minor issues which I found "on the way") and have released a new version of the app. You can
download it here:
https://github.com/mathisdt/trackworktime/releases/tag/v1.1.5 (use the signed package)

Google Play will take its time reviewing my update, I expect at least 2 days...

**Comment by iceaway** [comment]
Cool! Thanks for the quick fix! I'm not sure how to install APK:s so I'll wait for the play update :)

**Comment by iceaway** [comment]
I'm running 1.1.7 from Google Play now and it seems that wifi-tracking is still not working. If I check permissions for the app it still says "Location" and "Storage", not sure if that means anything

**Comment by mathisdt** [comment]
That's strange. Could you please send your log file via the menu item in the app so I can investigate? As this functionality only sends the current day's logs, please use it *after* it should have clocked you in via Wi-Fi. Thanks!

**Comment by iceaway** [comment]
I sent you an e-mail at android@zephyrsoft.org with the logs.

**Comment by jahnf** [comment]
> I'm running 1.1.7 from Google Play now and it seems that wifi-tracking is still not working. If I check permissions for the app it still says "Location" and "Storage", not sure if that means anything

I guess I have the same issue - location tracking works but WiFi is not - will have to check  and send the logs tomorrow. (Android 11)

**Comment by mathisdt** [comment]
I received the logs and discovered another problem: the app didn't ask for all privileges which are necessary on Android 10+, ACCESS_FINE_LOCATION is required by the Android system to receive the Wi-Fi network names ([see documentation](https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-permissions)). 

This is fixed in version 1.1.8 which has yet to be published by Google Play store. You can install it already from Github ([see instructions](https://zephyrsoft.org/trackworktime/faq#install-lastest-apk)).
